apiVersion: v2
name: jenkins
description: Jenkins for Kubernetes 1.34+ (Bitnami via GitHub)
type: application
version: 0.1.0
appVersion: "2.462.1"

dependencies:
  - name: jenkins
    version: 15.5.3
    repository: https://raw.githubusercontent.com/bitnami/charts/main/bitnami
