jenkins:
  controller:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2
        memory: 4Gi

    ingress:
      enabled: true
      className: nginx 
      path: /
      hosts:
        - jenkins.localhost
      tls:
        - secretName: jenkins-tls
          hosts:
            - jenkins.localhost

    # Service
    serviceType: ClusterIP
    servicePort: 8080
    httpPort: 8080

    adminUser: admin
    adminPassword: admin 

    installPlugins:
      - kubernetes:latest
      - workflow-aggregator:latest
      - git:latest
      - pipeline-stage-view:latest
      - configuration-as-code:latest  

    numExecutors: 0  
    containerAgent:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi

  persistence:
    enabled: true
    size: 10Gi
    storageClass: "" 

  rbac:
    create: true
  serviceAccount:
    create: true
    name: jenkins

  hostNetworking: false
  hostPID: false

